### PR TITLE
Make logging a compile option in order to support ewasm compatibility

### PR DESCRIPTION
**Pull request by AlexandreBelling**
Hey Matter-Labs team,

We are currently using bellman on an execution environment, and running it with scout. It runs great, the only thing we needed to change is to remove the logging capability. This PR adds the feature `nolog` which deactivate the logging capability.

In order to use bellman in an Eth2.0 EE, one would need to import it with:
```
features = ["wasm", "nolog"], default-features = false
```

I did it with a minimal amount of changes. For instance, I choosed to prefix all the `stopwatch` variable with an underscore (which, I agree, is not the cleaniest the way to deal with unused variable) instead of compiling out every occurence of `stopwatch` when `nolog` is enabled because that would be less maintainable.

Also, I made sure that this compile with:
* wasm
* sonic
* gm17

Please let me know, if you think anything should be changed

### CODE REVIEW

**Comment by shamatar** [comment]
@AlexandreBelling does `num_cpu` crate work in Eth2.0 EE by the way? I'd need to resolve this with a previous PR

**Comment by AlexandreBelling** [comment]
So the check with [num_cpus](https://crates.io/crates/num_cpus), yield posive results. As expected, `num_cpus::get()` returns 1 in the Eth2.0 EE context.

I did the check with the latest version, ie : `1.11.1`

**Comment by AlexandreBelling** [comment]
Just updated the PR to include the latest changes of `futures`

**Comment by shamatar** [comment]
@AlexandreBelling can you check for a new futures PR in WASM plus if you still need an adhoc multiexponentiation fix for MNT4/6 with 753 bits field?

**Comment by AlexandreBelling** [comment]
@shamatar 

Just made the update. The migration to future completely solved the problem with MNT4/6-753 and the eWasm compatibility is still functional

**Pull request merged**
